(require 'ert)
(require 'shell-split-string)

(ert-deftest test-shell-split-string ()
  (should (equal (shell-split-string "abc")
                 '("abc")))
  (should (equal (shell-split-string "abc def")
                 '("abc" "def")))
  (should (equal (shell-split-string "abc  def")
                 '("abc" "def")))
  (should (equal (shell-split-string "abc \"def\"")
                 '("abc" "def")))
  (should (equal (shell-split-string "abc 'def'")
                 '("abc" "def")))
  (should (equal (shell-split-string "abc  \"def\"")
                 '("abc" "def")))
  (should (equal (shell-split-string "abc \"def  ghi\"")
                 '("abc" "def  ghi")))
  (should (equal (shell-split-string "abc 'def  ghi'")
                 '("abc" "def  ghi")))
  (should (equal (shell-split-string "abc \"d\\\"ef\"")
                 '("abc" "d\"ef")))
  (should (equal (shell-split-string "abc \"d'ef\"")
                 '("abc" "d'ef")))
  (should (equal (shell-split-string "abc 'de f'ghi")
                 '("abc" "de fghi")))
  (should (equal (shell-split-string "abc def'gh i'")
                 '("abc" "defgh i")))
  (should (equal (shell-split-string "abc de'fg  h'i")
                 '("abc" "defg  hi")))
  (should (equal (shell-split-string "a\\bc")
                 '("abc")))
  (should (equal (shell-split-string "\"a\\bc\"")
                 '("a\\bc")))
  (should (equal (shell-split-string "'a\\bc'")
                 '("a\\bc")))
  )
