# http://www.kaichan.info/blog/2014-02-23-emacs-cask.html
language: emacs-lisp
before_install:
  # Install Emacs
  - sudo add-apt-repository -y ppa:cassou/emacs
  - sudo apt-get update -qq
  - sudo apt-get install -qq emacs24
script: make test
